# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "https://www.fzf404.top/favicon.svg"

[footer]
since = 2018

[dateFormat]
published = "2006-01-02"
lastUpdated = "2006-01-02 15:04"

[sidebar]
emoji = "ğŸ­"
subtitle = "ç†æƒ³ä¸»ä¹‰è€…"

[sidebar.avatar]
enabled = true
local = false
src = "https://www.fzf404.top/public/avatar.webp"

[article]
math = false
toc = true
readingTime = true

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "gitalk"

[comments.gitalk]
owner = "fzf404"
admin = "fzf404"
repo = "fzf404.github.io"
clientID = "96bc5e5937f5c57472ac"
clientSecret = "f04829c119b384505192de518b0d7ba8eac7e719"
